### PR TITLE
Backmerge changes from the bitbucket fork, that were accidently released to the public

### PR DESCRIPTION
**Pull request by sweh**
Unfortunately I am not able to get the tests to run in a fresh environment (even those in the current master). If you experience test failures that are introduced by my changes, feel free to get in touch with me so we can fix them together.

### CODE REVIEW

**Comment by sweh** [comment]
Tests are failing on Travis because to postgres server is running.

**Comment by icemac** [comment]
Thank you for the RP, we'll look into it the next time, we regularly work on our open source projects.

**Comment by vernans** [comment]
Hey @sweh, we're working on a new release for this package so we repaired the travis-ci integration of this package. I hope this helps you, you could try to rebase your changes and hope for travis to run your tests!

**Comment by sweh** [comment]
Hi @vernans, all tests seem to fail because of a `Lost connection to MySQL server during query`. Is this a bug that I introduced with my changes (which are mainly for postgresql, but can affect the mysql stuff because I changed the base class) or is this a travis problem? As I don't deploy MySQL on my local machine I am not able to run those tests for my own.

**Comment by icemac** [comment]
I needed the feature to set the port to access the database, so I releases a version 5.0 without these changes. I am going to to create a new pull request with the things from this PR which seem reasonable. After that I'll report back if there is anything that didn't make it into 5.x.

**Comment by icemac** [comment]
0820775 (Add standalone postgres server via `pyembedpg`.) did not make it into #9, as it does not have a test and using a database port is solved differently in 5.0 (but there for MySQL and PostgreSQL).

I am closing this PR in favor of #9.

**Pull request closed without merging**
