### PR TITLE
Sqlalchemy2

### LINKED ISSUE #35: Add support for SQLAlchemy 2.x
SQLAlchemy 2.0 breaks the tests, see https://github.com/gocept/gocept.testdb/actions/runs/4096454718/jobs/7064111752
So #34 restricts this project to SQLAlchemy < 2.

There should be a v2 compatibility mode in v1.4 but we do not seem to have it activated, so the v2 breaking was a bit of a surprise.

### PR DESCRIPTION
**Pull request by ni-rnias**
Resolves #35.

I updated tox so that tests are run for multiple versions of SQLAlchemy.

SQLAlchemy 2.x drops support for Python 2.7. I went further and dropped support for 3.6 and 3.7 as well, since these are EoL. Potentially these could still be supported, I haven't tried testing them.

I also added support for Python 3.10 and 3.11, which implied dropping support for SQLAlchemy before 1.2. This could potentially be split into a different PR if needed.

### CODE REVIEW

**Comment by icemac** [comment]
Hi @ni-rnias, thank you for your PR. Sorry that I overlooked it and removed support for older Python versions myself in a separate PR. Maybe I'll find the time in the next days to resolve the conflicts.

**Comment by ni-rnias** [comment]
I had some time so quickly resolved the conflicts.

I noticed that your PR didn't explicitly drop support for py3.7, but it did remove it from the tox env list. I put it back in there and the tests appear to pass, so it looks like support for 3.7 is still possible. Whether this is desirable, I don't know, since 3.7 is EoL since around 2 months ago.

**Comment by ni-rnias** [comment]
Seems like coverage fell because I removed some unneeded lines that were previously covered.

Also, since I changed the github actions matrix, the "expected checks" don't exist anymore.

**Review by icemac — APPROVED** [review]
LGTM, thank you for this PR.

**Comment by icemac** [comment]
I just released https://pypi.org/project/gocept.testdb/6.0/.

**Pull request merged**
